
package frec.jcm.awt;

/**
 * This class is from edu.hws.jcm.awt package without any modification.
 * JCMErrors can be generated by objects belonging to various classes
 * in edu.hws.jcm.awt and edu.hws.jcm.draw.  A JCMError can have an 
 * associated object, which is generally a ParseContext, InputObject,
 * or Computable.
 *
 * @author David Eck
 */
public class JCMError extends RuntimeException {
   /**
    * Object, possibly null, associated with this error.
    */
   public Object object;

   /**
    * Create a JCMError with the given error message and no associated object.
    *
    * @param message the error message associated with this JCMError.
    */
   public JCMError(String message) {
      this(message,null);
   }

   /**
    * Create a JCMError with the given error message and associated object.
    *
    * @param message the error message associated with this JCMError.
    * @param object the object associated with this JCMError.
    */
   public JCMError(String message, Object object) {
      super(message);
      this.object = object;
   }
}
